config/routes.rb
Rails.application.routes.draw do

  resources :bags
  devise_for :users
  root "pages#home"
  get 'dashboard' => "pages#dashboard"
  post '/buy/:slug', to: 'transactions#create', as: :buy 
  get '/pickup/:guid', to: 'transactions#pickup', as: :pickup

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       can :read, :all 
       can :manage, Bag do |bag|
        bag.try(:user) == user 
       end
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/bag.rb
class Bag < ActiveRecord::Base
	extend FriendlyId
	friendly_id :name, use: :slugged

	belongs_to :user
	has_many :sales
	has_attached_file :image

	validates_attachment_content_type :image, 
	content_type: /^image\/(png|gif|jpeg)/,
    message: "Only images allowed"

    validates :image, attachment_presence: true

    validates_numericality_of :price,
    greater_than: 49, message: "Must be at least 50 cents"
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	before_create :populate_guid
	belongs_to :bag 

	include AASM
	
aasm column: 'state' do
	state :pending, initial: true
	state :processing
	state :finished
	state :errored
	
	event :process, after: :charge_card do
		transitions from: :pending, to: :processing
	end
	
	event :finish do
		transitions from: :processing, to: :finished
	end
	
	event :fail do 
		transitions from: :processing, to: :errored
	end
end

def charge_card
   begin
	save!
	charge = Stripe::Charge.create(
		amount: self.amount,
		currency: "usd",
		card: self.stripe_token,
		description: "Bag Sale"
		)
	self.update(stripe_id: charge.id)
	self.finish!
   rescue Stripe::StripeError => e
	self.update_attributes(error: e.message)
	self.fail!
   end
   
end 
	private 

	def populate_guid
		self.guid = SecureRandom.uuid()
	end 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :bags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception| 
  	redirect_to root_path, notice: "You are not authorized to access this area"
  end 
end

app/controllers/bags_controller.rb
class BagsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_bag, only: [:show, :edit, :update, :destroy]

   respond_to :html

  def index
    @bags = Bag.where(availability: true)
    respond_with(@bags)
  end

  def show
    respond_with(@bag)
  end

  def new
    @bag = Bag.new
    respond_with(@bag)
  end

  def edit
    authorize! :manage, @bag
  end

  def create
    @bag = current_user.bags.new(bag_params)
    @bag.save
    respond_with(@bag)
  end

  def update
    authorize! :manage, @bag
    @bag.update(bag_params)
    respond_with(@bag)
  end

  def destroy
    authorize! :manage, @bag
    @bag.destroy
    respond_with(@bag)
  end

  private
    def set_bag
      @bag = Bag.friendly.find(params[:id])
    end

    def bag_params
      params.require(:bag).permit(:name, :author, :description, :price, :availability, :image, :resource)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  before_action :authenticate_user!, only: [:dashboard]

  def home
  	if current_user 
  		redirect_to bags_path
  end
end

def dashboard
	@bags = current_user.bags
	@purchased = Sale.where(buyer_email: current_user.email)
    @sales = Sale.where(seller_email: current_user.email)
	end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def create
  	bag  = Bag.find_by!(slug: params[:slug])
    sale = bag.sales.create(
      amount: bag.price,
          buyer_email: current_user.email,
          seller_email: bag.user.email,
          stripe_token: params[:stripeToken])
       sale.process!

       if sale.finished?
  redirect_to pickup_url(guid: sale.guid), notice: "Transaction Successful"
       else
  redirect_to bag_path(bag), notice: "Something went wrong"
       end
  
end


  def pickup
    @sale = Sale.find_by!(guid: params[:guid])
    @bag = @sale.bag
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bags_helper.rb
module BagsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bags/_bag.html.erb
<div class="col-md-3">
<div class="thumbnail">
<%= link_to bag_path(bag) do %>
<%= image_tag bag.image.url(:original), class: "img-responsive" %>
<% end %>

<div class="caption">
<p><strong><%= link_to bag.name, bag_path(bag) %></strong></p>
<p>$<%= bag.price.to_f / 100 %></p>
</div>
</div>
</div>

app/views/bags/_form.html.erb
<%= simple_form_for(@bag, htmk: {class: "form-signin"}) do |f| %>
  <%= f.error_notification %>

  
    <%= f.input :name, required: true, label: false, placeholder: "Name", input_html: {class: "form-control"} %>
    <%= f.input :brand, required: true, label: false, placeholder: "Brand",input_html: {class: "form-control"} %>
    <%= f.input :description, required: true, label: false, placeholder: "Descripton",input_html: {class: "form-control", rows: 5 } %>
    <%= f.input :price, required: true, label: false, placeholder: "Price",input_html: {class: "form-control"} %>
    <%= f.input :image %>

    <div class="checkbox text-center">
      <p>Availability<p>
    <%= f.input :availability, required: false, label: false%>
  </div>


    <%= f.button :submit, class: "btn btn-primary btn-block" %>

<% end %>

app/views/bags/edit.html.erb
<h1 class="text-center">Editing Bag</h1>

<%= render 'form' %>

<%= link_to 'Show', @bag %> |
<%= link_to 'Back', bags_path %>

app/views/bags/index.html.erb
<div class="container">
<div class="row">

<%= render @bags %>

</div>
</div>

app/views/bags/new.html.erb
<h1 class="text-center">New Bag</h1>

<%= render 'form' %>

<%= link_to 'Back', bags_path %>

app/views/bags/show.html.erb
<div class="container">
<div class="row">
 
<div class="col-md-6">
<%= image_tag @bag.image.url(:original), class: "img-responsive" %>
</div>

<div class="col-md-6">
<h3><%= @bag.name %> by <%= @bag.brand %></h3>
<p class="justify"><%= @bag.description %></p>
<h4 class="text-right">$<%= @bag.price.to_f / 100 %></h4>

<% if current_user %>

<%= form_tag buy_path(slug: @bag.slug) do %>
<script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-amount="<%= @bag.price %>"
    data-name="Vicky's"
    data-description="<%= @bag.name %>"
    data-email="<%= current_user.email %>">
  </script>
<% end %>


<% else %>

<p>Please Login First to Buy</p>

<% end %>
</div>
 
</div>
</div>

<%= link_to 'Edit', edit_bag_path(@bag) %> |
<%= link_to 'Back', bags_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Vicky's", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Bags", bags_path %><li>
        <% if current_user %>
        <li><%=link_to "Settings", edit_user_registration_path %></li>
        <li><%=link_to "Dashboard", dashboard_path %></li>
        <li><%=link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrBag</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>
<div class = "container">
	<% flash.each do |type, message| %>
	<div class = "alert alert-info fade-in">
		<button class = "close" data-dismiss = "alert">x</button>
		<%= message %>
	</div>
	<% end %>
<%= yield %>
</div>
</body>
</html>

app/views/pages/_purchased.html.erb
<table class="table table-condensed">
      <thead>
        <tr>
          <th>Name</th>
          <th>Date</th>
        </tr>
      </thead>
      <tbody>
      <% @purchased.each do |sale| %>
        <tr>
          <td><%= link_to sale.bag.name, pickup_path(sale.guid) %></td>
          <td><%= time_ago_in_words(sale.created_at) %> ago</td>
        </tr>
        <% end %>
      </tbody>
    </table>

app/views/pages/_sales.html.erb
<table class="table table-condensed">
      <thead>
        <tr>
          <th>Name</th>
          <th>Date</th>
          <th>Buyer</th>
        </tr>
      </thead>
      <tbody>
      <% @sales.each do |sale| %>
        <tr>
          <td><%= link_to sale.bag.name, pickup_path(sale.guid) %></td>
          <td><%= time_ago_in_words(sale.created_at) %> ago</td>
          <td><%= sale.buyer_email %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

app/views/pages/dashboard.html.erb
<div class="container">
<div class="row">
<h1 class="text-center">Dashboard</h1>
<div class="text-center"><%= link_to "New Bag", new_bag_path, class: "btn btn-primary btn-sm" %></div>
<div class="clearfix"></div>
<div class="col-md-4">
<div class="dash-box">
<h4 class="white uppercase">
Bags
</h3>
</div>
<table class="table table-condensed">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Available</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% @bags.each do |bag| %>
        <tr>
          <td><%= bag.id %></td>
          <td><%= link_to bag.name, bag_path(bag) %></td>
          <td><%= bag.availability %></td>
          <td><%= link_to "Edit", edit_bag_path(bag) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
</div>
<div class="col-md-4">
<div class="dash-box">
<h4 class="white uppercase">
Purchased
</h3>
</div>
<%= render "purchased" %>
</div>
<div class="col-md-4">
<div class="dash-box">
<h4 class="white uppercase">
Sales
</h3>
</div>
<%= render "sales" %>
</div>
</div>
</div>

app/views/pages/home.html.erb
<div class="background-image">
<div class="container">
<div class="col-lg-6 col-lg-offset-3">
<div class="jumbotron text-center">
<h2 class="uppercase">Welcome to Vicky's</h2>
<p>The largest online Marketplace for bags and purses</p>
<%= link_to "Bags", bags_path, class: "btn btn-primary btn-block" %>
<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-block" %>
</div>


</div>
<div class="clearfix"></div>
<div class="row">




</div>
</div>
</div>

app/views/transactions/pickup.html.erb
<div class="row text-center">
<h1>Congratulations on your order <%= @sale.guid %></h1>
<p>The owner of this item will ship it soon! Check your email for further confirmation</p>
</div>